Update SIGTERM signal handler so we only try to log a message if the log handlers are still open.
By default, agent_main.py stop command tries to send SIGTERM signal to
the agent for up to 5 seconds with short sleep in between each attempt.

On SIGTERM we invoke a termination handler which also closes all the
log handlers.

This means that subsequent SIGTERM signal handlers will try to log
a message when all the handlers will already be closed which will cause
users to see many of the following errors in stdout:

IOError: [Errno 0] Error
Logged from file platform_posix.py, line 637
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 889, in emit
    stream.write(fs % msg)