AGENT-402: Use `max_send_rate_enforcement` to rate limit sent log bytes (#551)
* AGENT-401: Implement new send rate defaults and fallback switches

* Update copying manager tests

* Test to see if defaults are causing smoketests to fail

* Revert test to see if defaults are causing smoketests to fail

* To make it easier to troubleshoot, log collectors which were found.

* Make sure we only perform agent version check once.

This check operates against local agent.log file so there is no need to
wait on Scalyr API and retry on potential missing data (which indicates
that the agent may not have sent the data yet or it hasn't been fully
processed by the API yet).

* Log how many matches were found to make it easier to troubleshoot.

* Test a change - if file exists already, re-open it instead of modifying
mtime + atime.

* Test another change - don't pre-create the file.

* Remove testing change, reduce sleep.

* Print agent status on timeout / failure. This may help with
troubleshooting.

* Test another change.

* Remove testing change.

* Change max_allowed_request_size to test smoketest issues

* Continue trying to narrow down problematic config option

* Continue trying to narrow down problematic config option

* Continue trying to narrow down problematic config option

* Continue trying to narrow down problematic config option

* Continue trying to narrow down problematic config option

* Continue trying to narrow down problematic config option

* Testing change

* Try to narrow down where `--no-fork` causes issues

* Try sleeping on fork to prove race condition

* Make sure the fork is the actual cause

* Make sure the fork is the actual cause

* Test if flushing is enough to fix the issue

* Try a sleep to test race condition

* Test closing streams

* Test closing streams

* Test stream redirecting

* Test stream redirecting

* Test stream redirecting

* Test disabling debug logging

* Test lower but still enabled debug level

* Test not uploading debug logs

* Test not closing fds

* Test None stdin

* Test a change.

* Log a message when we successfully write status data to file.

* Set one new default back to old value for test

* Test old defaults

* Test old defaults

* Test old defaults (Disable a lot of CI tests for now)

* Test old defaults

* Test old defaults

* Test old defaults

* Add AgentLogFilter to every log handler.

That's the approach we used before #466 and #495 and it appears to fix
the test failure issue.

* Test handler change

* Test handler change

* Cleanup

* Cleaner values for base 2 values

* Remove test changes we don't need anymore.

* Don't call close() in case handler is none (aka if __recreate_handler()
return None).

* Fix StdoutFilter.

The filter wouldn't filter correctly if a custom value was provided for
stdout_severity configuration option because getattr(logging, 'LEVEL
NAME') returns reference to the logger function for that log level and
not the actual number which maps to that log level name.

For that, we need to use logging.getLevelName().

* Add TODO annotation.

* handler can be None if __recreate_handler() method returns None.

* Add changelog entry.

* Update SIGTERM signal handler so we only try to log a message if the log
handlers are still open.

By default, agent_main.py stop command tries to send SIGTERM signal to
the agent for up to 5 seconds with short sleep in between each attempt.

On SIGTERM we invoke a termination handler which also closes all the
log handlers.

This means that subsequent SIGTERM signal handlers will try to log
a message when all the handlers will already be closed which will cause
users to see many of the following errors in stdout:

IOError: [Errno 0] Error
Logged from file platform_posix.py, line 637
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 889, in emit
    stream.write(fs % msg)

* Make sure close_handlers() is called at the very end before shutting
down.

If we call it as part of run state stop callbacks, it means
close_handlers() will be called early on before stopping worker thread
which means that some messages produced after that function being called
and before agent actually shutting down will be lost.

* Make sure we call .upper() on the stdout severity string.

This way it works correctly when using getattr(logging, level) and we
don't accidentaly retrieve reference to some other logging module
variable which doesn't represent a log name.

For example, if user would pass in info, we would assume the level is
correct, but we would actially get a reference to logging.info function
and not the corresponding log level number.

* Add a very simple release note

* AGENT-402: Use `max_send_rate_enforcement` to rate limit sent log bytes

* Test updates and minor fix

* Leave notes to be in separate PR AGENT-406

* Review comments

* Test issues

* Test issues

* Test issues

* Add test for legacy overrides

* Review comments

* Use new configuration option

* Limit output of override warning

* Comment on RateLimiter bucket size

* Nicer comment format

* Spelling

* Better override values

* Test updates

* Add @return comment

Co-authored-by: Tomaz Muraus <tomaz@tomaz.me>