Fix multi stage context name and make sure it doesn't end with just "-" since context names ending just with "-" doesn't seem to be valid anymore with the latest docker / buildx versions.
> > error: failed to solve: failed to parse stage name "scalyr-dependencies-rust-": invalid reference format
sh -c 'docker rm -f agent_base_image_registry_step'
agent_base_image_registry_step

References:

* https://docs.docker.com/engine/release-notes/
* https://github.com/docker/buildx/releases